import { Controller, Get } from '@nestjs/common';

@Controller('static-data')
export class StaticDataController {
  @Get('terms-message')
  getTermsMessage() {
    return 'এটি বাংলাদেশ রেলওয়ে এর অফিশিয়াল এ্যাপ নয় । এটি একটি কমিউনিটি এ্যাপ ।\n\nএ্যাপটিতে বাংলাদেশ রেলওয়ে এর এপিআই ব্যবহার করে সবকিছু করা হয়েছে এবং এই এপিআই গুলোর অপব্যবহার করা হয়নি ।\n\nবাংলাদেশ রেলওয়ে চাইলে আমরা এই এ্যাপটি বন্ধ করতে বাধ্য ।';
  }

  @Get('train-names')
  getTrainNames() {
    return {
      'BANGLABANDHA EXPRESS': 'বাংলাবান্ধা এক্সপ্রেস',
      'CHATTALA EXPRESS': 'চট্টলা এক্সপ্রেস',
      'DHALARCHAR EXPRESS': 'ঢালারচর এক্সপ্রেস',
      'DOLONCAPA EXPRESS': 'দোলনচাপাঁ এক্সপ্রেস',
      'EGARO_SINDUR PROVATI': 'এগারো সিন্ধুর প্রভাতী',
      'EID SPACHIAL': 'ঈদ স্পেশাল',
      'EID SPECIAL 1': 'ঈদ স্পেশাল ১',
      'EID SPECIAL-4': 'ঈদ স্পেশাল ৪',
      'KAROTOYA EXPRESS': 'করতোয়া এক্সপ্রেস',
      'KOROTAYA EXPRESS': 'করতোয়া এক্সপ্রেস',
      'MOHANAGAR EXPRESS': 'মহানগর এক্সপ্রেস',
      'MOHONGANJ EXPRESS': 'মোহনগঞ্জ এক্সপ্রেস',
      'PADMA EXPRESS': 'পদ্মা এক্সপ্রেস',
      'RUPSA EXPRESS': 'রুপসা এক্সপ্রেস',
      'SEEMANTA EXPRESS': 'সীমান্ত এক্সপ্রেস',
      'SHAGOR DARI_EXPRESS': 'সাগরদাঁড়ি এক্সপ্রেস',
      'SONAR BANGLA': 'সোনার বাংলা',
      'TUNGIPARA EXPRESS': 'টুঙ্গিপাড়া এক্সপ্রেস',
      AUGNIBINA_EXPRESS: 'অগ্নিবীণা এক্সপ্রেস',
      BANALATA_EXPRESS: 'বনলতা এক্সপ্রেস',
      BENAPOLE_EXPRESS: 'বেনাপোল এক্সপ্রেস',
      BIJOY_EXPRESS: 'বিজয় এক্সপ্রেস',
      BORENDRA: 'বরেন্দ্র',
      BRAHMAPUTRA: 'ব্রক্ষপুত্র',
      CHATTALA: 'চট্টলা',
      CHITRA: 'চিত্রা',
      COMMUTER: 'কমিউটার',
      DHUMKATU_EXPRESS: 'ধূমকেতু এক্সপ্রেস',
      DN_CTG_SPECIAL: 'ডিএন সিটিজি স্পেশাল',
      DRUTAJAN_EXPRESS: 'দ্রুতযান এক্সপ্রেস',
      EGARO_SINDUR_GODHULI: 'এগারো সিন্ধুর গোধূলী',
      EKOTA_EXPRESS: 'একতা এক্সপ্রেস',
      HAOWR_EXPRESS: 'হাওর এক্সপ্রেস',
      INTERCITY_COMMUTER: 'আন্তঃনগর কমিউটার',
      JAMALPUR_EXPRESS: 'জামালপুর এক্সপ্রেস',
      JAMUNA_EXPRESS: 'যমুনা এক্সপ্রেস',
      JOYENTEEKA: 'জয়ন্তিকা',
      KALNI_EXPRESS: 'কালনী এক্সপ্রেস',
      KISHOREGANJ_EXPRESS: 'কিশোরগঞ্জ এক্সপ্রেস',
      KOPOTAKHA_EXPRESS: 'কপোতাক্ষ এক্সপ্রেস',
      KURIGRAM_EXPRESS: 'কুড়িগ্রাম এক্সপ্রেস',
      LALMONI_EXPRESS: 'লালমনি এক্সপ্রেস',
      MAHANAGAR_GODHULI: 'মহানগর গোধূলী',
      MAHANAGAR_PROVATI: 'মহানগর প্রভাতী',
      MEGHNA_EXPRESS: 'মেঘনা এক্সপ্রেস',
      MODHUMATI_EXPRESS: 'মধুমতী এক্সপ্রেস',
      NELSAGORE_EXPRESS: 'নীলসাগর এক্সপ্রেস',
      PADMA: 'পদ্মা',
      PAHARIKA_EXPRESS: 'পাহাড়িকা এক্সপ্রেস',
      PANCHAGARH_EXPRESS: 'পঞ্চগড় এক্সপ্রেস',
      PARABAT_EXPRESS: 'পারাবত এক্সপ্রেস',
      RANGPUR_EXPRESS: 'রংপুর এক্সপ্রেস',
      SILKCITY_EXPRESS: 'সিল্কসিটি এক্সপ্রেস',
      SILKCITY: 'সিল্কসিটি',
      SIRAJGANJ_EXPRESS: 'সিরাজগঞ্জ এক্সপ্রেস',
      SPECIAL_TRAIN: 'স্পেশাল ট্রেন',
      SUBARNA_EXPRESS: 'সুবর্ণ এক্সপ্রেস',
      SUNDARBAN_EXPRESS: 'সুন্দরবন এক্সপ্রেস',
      TISTA_EXPRESS: 'তিস্তা এক্সপ্রেস',
      TITUMIR: 'তিতুমীর',
      TURNA_EXPRESS: 'তূর্ণা এক্সপ্রেস',
      UDAYAN: 'উদয়ন',
      UPABAN_EXPRESS: 'উপবন এক্সপ্রেস',
      UPAKUL_EXPRESS: 'উপকূল এক্সপ্রেস',
    };
  }

  @Get('locations')
  getLocations() {
    return {
      ABDULPUR: 'আব্দুলপুর',
      ACCALPUR: 'আক্কেলপুর',
      AHASANGANG: 'আহসানগঞ্জ',
      AKHAURA: 'আখাউড়া',
      ALAMDANGA: 'আলমডাঙ্গা',
      ASHUGANJ: 'আশুগঞ্জ',
      AZAMPUR: 'আজমপুর',
      'B SIRAJUL ISLAM': 'বীর মুক্তিযোদ্ধা সিরাজুল ইসলাম',
      BAJITPUR: 'বাজিতপুর',
      BANANI: 'বনানী',
      BBSETU_E: 'বঙ্গবন্ধুসেতু/পূ:',
      BENAPOLE: 'বেনাপোল ',
      BHAIRAB_BAZAR: 'ভৈরববাজার',
      BHAIRAMARA: 'ভেড়ামারা',
      BHANUGACH: 'ভানুগাছ',
      BIMAN_BANDAR: 'বিমান বন্দর',
      BIRAMPUR: 'বিরামপুর',
      BONAR_PARA: 'বোনারপাড়া',
      BORAL_BRIDGE: 'বড়াল ব্রিজ',
      BORASHI: 'বোড়াশী',
      BRAHMAN_BARIA: 'ব্রাক্ষণবাড়িয়া',
      CHANDPUR: 'চাঁদপুর',
      CHAPAINABABGANJ: 'চাঁপাইনবাবগঞ্জ',
      CHAPTA: 'চাপতা',
      CHATMOHAR: 'চাটমোহর',
      CHILAHATI: 'চিলাহাটি',
      CHITTAGONG: 'চট্টগ্রাম',
      CHUADANGA: 'চুয়াডাঙ্গা',
      COMILLA: 'কুমিল্লা',
      'COURT CHANDPUR': 'কোর্টচাঁদপুর',
      DARSANA_HALT: 'দর্শনা হলট',
      DA_CANTONMENT: 'ক্যান্টনমেন্ট',
      DEWANGANJ_BAZAR: 'দেওয়ানগঞ্জ বাজার',
      DHAKA: 'ঢাকা',
      DINAJPUR: 'দিনাজপুর',
      FENI: 'ফেনী',
      GAFARGAON: 'গফরগাঁও',
      GAIBANDHA: 'গাইবান্ধা',
      GOBRA: 'গোবরা',
      GOPALGANJ: 'গোপালগঞ্জ',
      GOURIPUR_MYN: 'গৌরীপুর ময়মনসিংহ',
      GUNABOTI: 'গুণবতী',
      ISHURDI: 'ঈশ্বরদী',
      ISLAMPUR_BAZAR: 'ইসলামপুর বাজার',
      JAMALPUR_TOWN: 'জামালপুর টাউন',
      JAYDEBPUR: 'জয়দেবপুর',
      JESSORE: 'যশোর',
      JHIKARGACHA: 'ঝিকরগাছা',
      JOYPURHAT: 'জয়পুরহাট',
      KASHIANI: 'কাসিয়ানী',
      KHULNA: 'খুলনা',
      KISHOREGANJ: 'কিশোরগঞ্জ',
      KULAURA: 'কুলাউড়া',
      KULIARCHAR: 'কুলিয়ারচর',
      KURIGRAM: 'কুড়িগ্রাম',
      LAKSAM: 'লাকসাম',
      LALMONIR_HAT: 'লালমনিরহাট',
      MAIZGAON: 'মাইজগাঁও',
      MELANDAH_BAZAR: 'মেলান্দহ বাজার',
      MOHONGANJ: 'মোহনগঞ্জ',
      MYMENSINGH: 'ময়মনসিংহ',
      NARSINGDI: 'নরসিংদী',
      NATORE: 'নাটোর',
      NAYAPARA: 'নয়াপাড়া',
      NEELFAMARI: 'নীলফামারী',
      NETROKONA: 'নেত্রকোনা',
      NOAKHALI: 'নোয়াখালী',
      PARBATIPUR: 'পার্বতীপুর',
      PHULBARI: 'ফুলবাড়ি',
      PORADAHA: 'পোড়াদহ',
      QOSBA: 'কসবা',
      RAJSHAHI: 'রাজশাহী',
      'RAJSHAHI COURT': 'রাজশাহী কোর্ট',
      RANGPUR: 'রংপুর',
      SAIDPUR: 'সৈয়দপুর',
      SANTAHER: 'সান্তাহার',
      SARARCHAR: 'সরারচর',
      SARISHA_BARI: 'সরিষাবাড়ি',
      'SH M MONSUR ALI': 'শহীদ এম মনসুর আলী',
      SHAISTAGONJ: 'শায়েস্তাগঞ্জ',
      SHAMSHERNAGAR: 'শমশেরনগর',
      SRIMANGAL: 'শ্রীমঙ্গল',
      SYLHET: 'সিলেট',
      TANGAIL: 'টাংগাইল',
      THAKURGAON_ROAD: 'ঠাকুরগাঁও রোড',
      ULLAPARA: 'উল্লাপাড়া',
    };
  }

  @Get('cabins')
  getCabins() {
    return {
      SNIGDHA: 'স্নিগ্ধা',
      S_CHAIR: 'শোভন চেয়ার',
      SHOVAN: 'শোভন',
      AC_B: 'এসি বাথ',
      AC_S: 'এসি সিট',
      F_BERTH: 'ফার্স্ট ক্লাস বাথ',
      F_SEAT: 'ফার্স্ট ক্লাস সিট',
      F_CHAIR: 'ফার্স্ট ক্লাস চেয়ার',
    };
  }
}
